emilyperica/ScoreGen

docs/DevelopmentPlan/DevelopmentPlan.tex

Team charter section
Issue #12 
Team charter section

Issue #12: Team charter

---

docs/DevelopmentPlan/DevelopmentPlan.tex

Issue #15 
Added sections 1, 2, 3 and 11

Issue #15: Code ownership

---

docs/DevelopmentPlan/DevelopmentPlan.tex
docs/ProblemStatementAndGoals/ProblemStatement.tex

Issue #4 
Added Reflection questions

Issue #4: Reflection questions

---

docs/DevelopmentPlan/DevelopmentPlan.tex
docs/ProblemStatementAndGoals/ProblemStatement.tex

Issue #4 
Added my personal reflections as required for the development plan an problem statement tex files.
Rendered PDFs locally.

Issue #4: Mark's reflections on Dev Plan and Problem Statement docs

---

docs/SRS-Volere/SRS.tex
docs/SRS/SRS.tex
docs/SRS_Reflection.tex

Merging changes from the template repo

---

docs/SRS-Volere/SRS.tex

Issue #39
Requirements sections for issue 39
Compiled pdf locally

Issue #39: Performance and Operation Requirements

---

docs/SRS-Volere/SRS.tex

Issue #61
title.
Compiled pdf locally

Issue #61: Adding functional requirements to SRS

---

docs/SRS-Volere/SRS.tex

Issue #59: Addition of Ideas for Solution section to SRS

---

docs/SRS-Volere/SRS.tex
docs/SRS-Volere/references.bib

Issue #78 
Bibtex
compiled locally

Issue #78: Added BibTeX for citations

---

docs/SRS-Volere/SRS.tex

Issue #40
title.
Compiled PDF locally

Issue #40: Addition of security and maintainability NFRs

---

docs/SRS-Volere/SRS.tex

Issue #66 
SRS project management documentation
Google Doc spell check

Issue #66: Add requirement sections on project management

---

docs/SRS-Volere/SRS.tex

Issue#59: Glossary

---

docs/SRS-Volere/SRS.tex

Issue #41
Addition to section 16 and 17 of SRS tex
google doc spell check

Issue #41: SRS user related requirements addition

---

docs/SRS-Volere/SRS.tex

added a package explicitly
Issue #59 
added package
local

Issue #59: Compile issue

---

docs/SRS-Volere/SRS.tex

Issue #59: added section 25, edited doc title and revision table date

---

docs/HazardAnalysis/HazardAnalysis.tex

Issue #101 
Added roadmap and new requirements sections (I couldn't for the life of me think of any requirements that weren't just re-worded versions of others)
compiled locally

Issue #101: roadmap and new reqs

---

docs/HazardAnalysis/HazardAnalysis.tex

Issue #99
Added my personal reflection answers and answer to the team reflection question 3. 
Local compile

Issue #99: add Ian's reflections and team question 3

---

docs/HazardAnalysis/HazardAnalysis.tex

Issue #99 
Mark Kogan's personal reflections
Local rendering

Issue #99: Mark Reflections on Hazard Analysis

---

docs/HazardAnalysis/HazardAnalysis.tex

Issue #102 
added section 3 system boundaries and components
local compile

Issue #102: add HA section 3 system components

---

docs/VnVPlan/VnVPlan.tex

Issue #120
Title.
Compiled locally.

Issue #120: Addition of 3.1 in VnV Plan

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

Issue #116 
Documentation written of VnVPlan section 3
Local compilation

Issue #116: VnV plan documentation

---

docs/VnVPlan/VnVPlan.tex

Issue #120: Adding usability survey to VnV plan

---

docs/VnVPlan/VnVPlan.tex

Issue #117 
add sections 4.1, 4.3, 6.1 to VnV plan
local compile

Issue #117: VnV functional requirements

---

docs/VnVPlan/VnVPlan.tex

Issue #122: Partial addition of reflections and doc formatting

---

docs/VnVPlan/VnVPlan.tex

Issue #122
added my reflection
compiled locally

Issue #122: Jackson Reflection

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

Issue #119
title
compiled locally

Issue #119: NFRs for VnV

---

docs/VnVPlan/VnVPlan.tex
refs/References.bib

Issue #122 
added sources for testing files to References.bib and added corresponding citation in VnV.tex appendix 
local compile

Issue #122: add testing file references

---

docs/VnVPlan/VnVPlan.tex

Issue #160 
Addressing peer review on FR test cases. Added one line justifications, adjusted some terminology to be more consistent.
Locally compiled.

Issue #160: add FR test case justifications, improve consistency

---

CMakeLists.txt
include/findKey.h
src/findKey.cpp

Issue #170 
Wrote the basic implementation of the [Krumhansler-Schumkler](http://rnhart.net/articles/key-finding/) key-detection algorithm. Not optimized (i.e., if a note has a 0 duration it is most likely not the key) and doesn't cover edge cases (i.e., will output its best guess without consideration for some other key with a close correlation coefficient).
Used the duration values from the above link as a test input. Produced the same correlation coefficients for all provided keys and produced the correct key. Formal unit tests tbd.

Issue #170: Implementing a key-detection algorithm

---

include/detectNoteDuration.h
src/ScoreGen.cpp
src/detectNoteDuration.cpp
src/detectNoteDuration.h
src/dsp.cpp

Issue #149 
Identify note lengths and classify them based off of tempo and time signature.
How it works: it's a super naive approach (for now), will definitely have to be revisited possibly being done at the same time as pitch detection to distinguish notes from more than just energy. But essentially this takes the length of music, splits it up into beats (for example the scale is 60 bpm and therefore is 1 second per beat), and from there, it splits the data up into what bytes correspond to each second. Each second is then analyzed to see if a note is being played in that beat, and when that note ends (to determine the type of note, quarter, half, etc). Then outputs the types of the notes at each beat
Work In Progress

Issue #149: Note Rhythms

---

CMakeLists.txt
include/recordAudio.h
src/ScoreGen.cpp
src/recordAudio.cpp
vcpkg.json

Issue #190 
Used various input and output devices for recording and playback.

Issue #190: Adding live audio processing

---

docs/Design/SoftArchitecture/MG.tex

Issue #194 
@ianzachary and I collaborated to identify the modules that make up ScoreGen.

Issue #194: Filling in section 5 of the Module Guide

---

docs/Design/SoftArchitecture/MG.tex

﻿## Issue #194 
Added links to figma and canva
compiled pdf locally

Issue #194: UI section

---

docs/Design/SoftDetailedDes/MIS.tex

Issue #195 
Added table from MG and some primitive 'types' we might be using
Compiled locally

Issue #195: MIS section 4 and 5

---

docs/Design/SoftDetailedDes/MIS.tex

Issue #197
Add final group reflections to MIS doc
Local pdf rendering

Issue #197: Insert reflections

---

docs/Design/SoftArchitecture/MG.tex

Issue #210
Added UI module refs where needed to align MG with FR_AI1 and FR_AI2.
Local render.

Issue #210: Edited Table 2 tracability

---

include/detectNoteDuration.h
src/backend/detectNoteDuration.cpp

Issue #184
First of a few PRs addressing issues with the current rhythm detection implementation. Added a Filter class and preprocessing function to be used in onset detection.

Issue #184: Filter class and preprocessing for future onset detection

---

include/detectNoteDuration.h
src/backend/dsp.cpp

Issue #184
Fixed minor syntax errors that slipped into main
Locally

Issue #184: Fix syntax errors

---

include/detectNoteDuration.h
src/backend/ScoreGen.cpp
src/backend/detectNoteDuration.cpp
src/backend/dsp.cpp

Issue #184
Added a silence threshold for detecting rest onsets, and adjusted threshold values to improve pitch detection.

Issue #184: Rest detection and fixing pitch detection

---

ScoreGen.Tests/CMakeLists.txt
ScoreGen.Tests/findKey.Test.cpp
ScoreGen.Tests/generateMusicXML.Test.cpp
include/generateMusicXML.h

Issue #185
Ian added tests with pipeline fix from mark for libmusicxml
local + CI

Issue #185: Adding utests for mXML generation, findKey methods

---

docs/VnVReport/VnVReport.tex

Issue #278
Just adding formatting, no actual test results.

Issue #278: Adding FRs from VnV plan

---

docs/VnVReport/VnVReport.tex

Issue #272
Title.
Rendered locally.

Issue #272: Adding unit test tables and failure explainations

---

docs/VnVReport/VnVReport.tex

Issue #277
NFR Test Results
all included in documentation. compiled pdf locally

Issue #277: NonFunctional Test Documentation

---

docs/VnVReport/VnVReport.tex

Issue #281
Title.
Local rendering.

Issue #281: Adding summary of feedback-related changes in section 7

---

docs/VnVReport/VnVReport.tex

Issue #278: Filling in FR test results

---

src/frontend/record.html
src/frontend/upload.html

Issue #320
Added alt and tooltip text
Local testing

Issue #320: Added alt and tooltip text

---

src/backend/ScoreGen.cpp
src/frontend/main.js
src/frontend/preload.js
src/frontend/record.html
src/frontend/record.js
src/frontend/styles.css

Issue #336 
Instead of exporting right away, create a dropdown and give user freedom to either save a musicxml, or go directly to creating a pdf
Local QA

Issue #336: Allow users to toggle between exporting musicXML and pdf

---

src/frontend/main.js
src/frontend/preload.js
src/frontend/sheet-music.html
src/frontend/sheet-music.js
src/frontend/styles.css

Issue #338 
Give user option to delete PDF to avoid clutter in pdf viewer window
Local QA

Issue #338: Allow deletion of PDF in pdf viewer

---

README.md

Issue #335 
About section in readme added
locally

Issue #335: Add main project blurb to README

---

src/backend/note_duration_extractor.cpp

Issue #344: Tweaking dsp values

---

src/frontend/record.html

Issue #349
Fixed the required pattern, make it required
Local

Issue #349: Fixed time signature bug, make it a required field

---

src/frontend/index.html
src/frontend/nav.js
src/frontend/record.html
src/frontend/sheet-music.html
src/frontend/styles.css
src/frontend/upload.html

Issue #346 
updated navbar and frontend home page
local

Issue #346: changed frontend names and buttons

---

src/frontend/main.js
src/frontend/record.html
src/frontend/record.js
src/frontend/styles.css

Issue #345 
Words indicating what is going on for user during loading of score generation
Locally
(If the loading drags on for long enough the text will change to "Generating output file...",
and finally  "Crunching final numbers..." but it rarely gets to these, our stuff actually loads quick af

Issue #345: Feedback during score generation loading
